version: "2"

linters:
  default: none
  enable:
  - asciicheck
  - bodyclose
  - errcheck
  - exhaustive
  - forcetypeassert
  - govet
  - ineffassign
  - noctx
  - predeclared
  - staticcheck
  - unused
  - whitespace
